"""add_ai_insights_table

Revision ID: 2d466131a71b
Revises: 
Create Date: 2026-04-20 17:20:38.630104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d466131a71b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_insights',
    sa.Column('id', sa.String(), nullable=False, comment='全局唯一洞察 ID（UUID）'),
    sa.Column('insights', sa.JSON(), nullable=False, comment='AI 洞察内容（JSON 数组格式）'),
    sa.Column('sample_count', sa.Integer(), nullable=True, comment='生成时使用的样本数量'),
    sa.Column('generated_by', sa.String(), nullable=True, comment='触发生成的用户ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_id'), 'ai_insights', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_insights_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    # ### end Alembic commands ###
