"""add_supplier_name_and_memory_tables

Revision ID: 2daac80a821b
Revises: 2d466131a71b
Create Date: 2026-04-24 19:56:39.636628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2daac80a821b'
down_revision: Union[str, Sequence[str], None] = '2d466131a71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_records', sa.Column('supplier_name', sa.String(), nullable=True, comment='供应商名称（从比对结果中提取）'))
    op.create_index(op.f('ix_task_records_supplier_name'), 'task_records', ['supplier_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_records_supplier_name'), table_name='task_records')
    op.drop_column('task_records', 'supplier_name')
    # ### end Alembic commands ###
