"""add model_name and processing_seconds to task_records

Revision ID: 930233c86571
Revises: 2daac80a821b
Create Date: 2026-05-05 23:20:15.580943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '930233c86571'
down_revision: Union[str, Sequence[str], None] = '2daac80a821b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_records', sa.Column('model_name', sa.String(length=100), nullable=True, comment='执行该任务时使用的底层大模型名称'))
    op.add_column('task_records', sa.Column('processing_seconds', sa.Integer(), nullable=True, comment='任务实际执行耗时（秒）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_records', 'processing_seconds')
    op.drop_column('task_records', 'model_name')
    # ### end Alembic commands ###
